version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      concord_net:
        name: concord_net
        ipv4_address: 192.168.88.2

  indexer:
    build: .
    depends_on:
      - postgres
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./.env
    volumes:
      - ./indexer/.env:/app/.env
    command: ["./entrypoint.sh"]
    networks:
      concord_net:
        name: concord_net
        ipv4_address: 192.168.88.3

  api:
    build: ./api
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    networks:
      concord_net:
        name: concord_net
        ipv4_address: 192.168.88.4

networks:
  concord_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.88.0/24

volumes:
  postgres-data:
